language: ruby
dist: xenial
sudo: required
cache:
  bundler: true
  directories:
  - vendor/bundle
before_install:
  - gem install bundler
install:
- bundle install
script:
- bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: GvoNDRn08iMnhjIkKOv06hcMY8aPDpOS5agCL6Z7up0CrLeHkA5JNLwrlmTRd6yiMP/QoHAotYk927OtUjQjdRKVR6udxssjvtZOnMoBb1XJBX7Y0E+ZegxmW48ndyA1Ei/RgGhRPtVT3Ye8yqXDXxQJbR+PpD2xDXPbjWen2MMURMc29+tm4lb5YEZw7OavpTXklIvzHM2fpArWXsWjkISj9uZvYfkI8Tu7bcg/2eUV2+rn5fukXuS5DQtP1e5HiFJU7Utkpr//AiXENNl+i3209BwVH5bfNATQDeuH4mXZS5fiujX0LsRNo4o4fk1YKfJjvUuokEc0wE/09qYG0iyHPq94pdedDT8xtYx+yNC7mZ1XPdoKGyBshbmxbzs3z8YV0rH4l6mgveEfGaCHw3L4rpU+NlT4aIZEr9d6xH/WiE9POkCM6oeYih+KIDntWwTLExjjeE8ZXbiZpYzDV+uPjRvubwv9Lj7h9UlAOzb4Npv60khmg4/hQ1H+u1MfV/IxXrJVAvQU+wX/SO81O/jFH4SEOB1kHdfMZZZYPgzSDjuyV0Vj13V8oTHCoW7PxfNrNJpAYU0G+BNKkmNdbetU4a4KMj3YuCw6Mb8Rq+aFHqsYEhU5qktLCIgCINJH9l/KwT4cWFBPu0HSTW3TegtktL/Yaw61N9XZPCrhnSU=
